apiVersion: v2
name: job-scheduler
description: Distributed Job Scheduler with real-time dashboard
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - job-scheduler
  - redis
  - postgresql
  - websocket
maintainers:
  - name: saikrishnans
